version: '3'

volumes:
  mysql_data:
  # cache:

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql_data/
    env_file:
      - docker.env
    networks:
      - mysql

  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning
  #   volumes:
  #     - cache:/data

networks:
  mysql:
    driver: bridge
